### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by huntzhan** [pywharf/pywharf-core#2]
# Active

## v0.2.0

Estimated release date: ~~`2020-02-19`~~ `2020-03-15` (kinda busy these days)

First public release. Goals:
1. Basic features like packages download/upload should be supported.
2. Extension mechanism, ~~Task management~~, CI, SOP.

Work items:

- [x] Local index synchronization daemon. (status: `done`, ETA: `2020-02-12`)
- [x] Better logging (logging to file & console in production; move all log files into a single folder). (status: `done`, ETA: `2020-02-14`, actual: `2020-02-15`)
- [X] Remove background task related code (will come up with a appropriate design in the next version). (status: `done`, ETA: `2020-02-16`, commit: cff2c8e5aaab079af5bc3983c3f544a69ebc46ba)
- [X] Backend architecture. Refactor `github.py` as standalone backend. (status: `done`, ETA: `n/a`)
- [x] Update https://github.com/private-pypi/private-pypi-sync-index . (status: `planned`, ETA: `n/a`)
- [x] Local file system backend. (status: `planned`, ETA: `n/a`)
- [x] Move github backend to  https://github.com/private-pypi/private-pypi-github; Rename `private-pypi` to `private-pypi-core`; Setup repo for release (core + backends).  (status: `planned`, ETA: `n/a`)
- [x] Setup project CI (`pytest`, `yapf`, ~~`pyright`~~). (status: `planned`, ETA: `n/a`)
- [ ] Support ~~`qiniu.com`~~ `ucloud` backend. (status: `planned`, ETA: `n/a`)
- [ ] Project contribution SOP.
- [ ] Docker images. Especially this enables user to use `private-pypi` in their GitHub workflow ([service container](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices)). (status: `planned`, ETA: `n/a`)
- [ ] Documentation: README. (status: `planned`, ETA: `n/a`) 
- [ ] PR, get beta user. (status: `planned`, ETA: `n/a`)

## Ideas

Will be implemented in the future.

Work items:

- Redesign background task management. (previous design 446f249278b1232360b135788a09541976cf1d38)
- Audit page (showing activity, task status & logs).
- Privatized deployment solution, including download all packages & dependencies and offline deployment guideline.
- `pip search` support.
- Local cache for package download.
- Free long unused objects in `SecretHashedStorage`.
- Better web UI.

# Template

## v0.0.0

Estimated release date: `yyyy-dd-mm`

[description]

Work items:

- [ ] [description] (status: `planned|engaging|done|deferred`, ETA: `yyyy-dd-mm`) 

# Archived

## v0.1.1

Register the package https://pypi.org/project/private-pypi/
